#ifndef Task_h
#define Task_h

#include "Arduino.h"

enum Task {
  TASK_ZERO_DROPPER = 0,
  TASK_START = 1,
  TASK_FIRE_CANNON_1 = 2,
  TASK_DELAY_CANNONS = 3,
  TASK_FIRE_CANNON_2 = 4,
  TASK_DELAY_MOVE = 5,
  TASK_MOVE_TO_MONEYBALL = 6,
  TASK_CAPTURE_MONEYBALL = 7,
  TASK_DRIVE_TO_CUPS = 8,
  TASK_DROP_BALLS = 9,
  TASK_RETURN = 10,
  TASK_STOP = 11
};

#endif
